modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "rumble-port"
version = "${version}"
displayName = "ROCK VR"
authors = "Omlettuce"
description = '''
Ports some gameplay elements from Buckethead Entertainment's RUMBLE to Minecraft
'''
logoFile = "icon.png"

[[dependencies.rumble-port]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rumble-port]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rumble-port]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.rumble-port]]
modId = "valkyrienskies"
mandatory = true
versionRange = "[2.4.0,)"
ordering = "AFTER"
side = "BOTH"
